### PR TITLE
feat: Support git-cinnabar URLs (bug 1784232)

### PR DESCRIPTION
**Pull request by JohanLorenzo**

### CODE REVIEW

**Comment by glandium** [comment]
See git-cinnabar's README, there are also hg:// urls.

**Comment by JohanLorenzo** [comment]
Thanks for pointing this to me. I did look at the README, but I stopped at this line: 

> ## Usage:
> ```
> $ git clone hg::<mercurial repo>
> ```
> where <mercurial repo> can be a path to a local directory containing a mercurial repository, or a http, https or ssh url.

I'll have a closer look at this paragraph, then[1]

[1] https://github.com/glandium/git-cinnabar/blob/235f8df93142c7195f0999834dc4a5fcd645621f/README.md#hg-urls

**Review by jcristau — CHANGES_REQUESTED** [review]
Requesting changes per glandium's comment.

**Comment by JohanLorenzo** [comment]
I just added support for the `hg://` URLs. If this looks good, I'll cut a new release and include the new version in mozilla-central. This way, the error in [1] should go away.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1784232#c23

**Review by jcristau — APPROVED** [review]
This looks fine, thanks.

As an aside I'd suggest limiting the exported API before we call this 1.0.

**Comment by JohanLorenzo** [comment]
Agreed! I was pondering on whether we should limit it or not. I'll handle it in a follow up, then 👍 

Thank you very much for this review!

**Pull request merged**
